package main

const (
	EXIT_SUCCESS                = 0
	EXIT_INVALID_ADDRESS        = -1
	EXIT_MISSING_PUBLIC_KEY     = -2
	EXIT_MISSING_SECRET_KEY     = -3
	EXIT_INVALID_PUBLIC_KEY     = -4
	EXIT_INVALID_SECRET_KEY     = -5
	EXIT_NO_SUCH_FILE           = -6
	EXIT_FILE_READ_ERROR        = -7
	EXIT_INVALID_LOCAL_CANARY   = -8
	EXIT_INVALID_REMOTE_CANARY  = -9
	EXIT_INVALID_OPERATION      = -10
	EXIT_INVALID_ARGUMENTS      = -11
	EXIT_BAD_PROXY              = -12
	EXIT_CONNECTION_FAILURE     = -13
	EXIT_INVALID_SIGNATURE      = -14
	EXIT_INVALID_CANARY         = -15
	EXIT_HTTP_UNEXPECTED_STATUS = -16
	EXIT_FILE_WRITE_ERROR       = -17
	EXIT_NEWS_RETRIEVE_ERROR    = -18
	EXIT_NEWS_READ_ERROR        = -19
)
